

var ocompterefencedata =[
  {
    "CompteNumber": "2811",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AE"
  }, {
    "CompteNumber": "2812",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AF"
  }, {
    "CompteNumber": "2813",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AF"
  }, {
    "CompteNumber": "2814",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AF"
  }, {
    "CompteNumber": "2815",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AG"
  }, {
    "CompteNumber": "2816",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AG"
  }, {
    "CompteNumber": "2817",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AH"
  }, {
    "CompteNumber": "2818",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AH"
  }, {
    "CompteNumber": "282",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AJ"
  }, {
    "CompteNumber": "2831",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AK"
  }, {
    "CompteNumber": "2832",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AK"
  }, {
    "CompteNumber": "2833",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AK"
  }, {
    "CompteNumber": "2837",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AK"
  }, {
    "CompteNumber": "283",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AL"
  }, {
    "CompteNumber": "284",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AM"
  }, {
    "CompteNumber": "2845",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblAmortImmo",
    "AreaShortName": "AmortImmo",
    "RefCode": "AN"
  }, {
    "CompteNumber": "485",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ActifCircul",
    "RefCode": "BA"
  }, {
    "CompteNumber": "486",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ActifCircul",
    "RefCode": "BA"
  }, {
    "CompteNumber": "488",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ActifCircul",
    "RefCode": "BA"
  }, {
    "CompteNumber": "25",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "AvanceAcpteImmo",
    "RefCode": "AP"
  }, {
    "CompteNumber": "206",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ChargesImmo",
    "RefCode": "AC"
  }, {
    "CompteNumber": "201",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ChargesImmo",
    "RefCode": "AX"
  }, {
    "CompteNumber": "202",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ChargesImmo",
    "RefCode": "AY"
  }, {
    "CompteNumber": "409",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BH"
  }, {
    "CompteNumber": "41",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BI"
  }, {
    "CompteNumber": "421",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "4287",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "4387",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "4449",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "445",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "4487",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "449",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "45",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "46",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "4711",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "475",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "476",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "CreancEmploi",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "478",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "EcartConvActif",
    "RefCode": "BU"
  }, {
    "CompteNumber": "22",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AJ"
  }, {
    "CompteNumber": "231",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AK"
  }, {
    "CompteNumber": "232",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AK"
  }, {
    "CompteNumber": "233",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AK"
  }, {
    "CompteNumber": "237",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AK"
  }, {
    "CompteNumber": "239",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AK"
  }, {
    "CompteNumber": "234",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AL"
  }, {
    "CompteNumber": "235",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AL"
  }, {
    "CompteNumber": "238",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AL"
  }, {
    "CompteNumber": "239",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AL"
  }, {
    "CompteNumber": "24",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AM"
  }, {
    "CompteNumber": "249",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AM"
  }, {
    "CompteNumber": "245",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AN"
  }, {
    "CompteNumber": "2495",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoCorpo",
    "RefCode": "AN"
  }, {
    "CompteNumber": "26",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoFinan",
    "RefCode": "AR"
  }, {
    "CompteNumber": "27",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoFinan",
    "RefCode": "AS"
  }, {
    "CompteNumber": "000",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoFinan",
    "RefCode": "AW"
  }, {
    "CompteNumber": "211",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoIncorp",
    "RefCode": "AE"
  }, {
    "CompteNumber": "2191",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoIncorp",
    "RefCode": "AE"
  }, {
    "CompteNumber": "212",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoIncorp",
    "RefCode": "AF"
  }, {
    "CompteNumber": "213",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoIncorp",
    "RefCode": "AF"
  }, {
    "CompteNumber": "214",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoIncorp",
    "RefCode": "AF"
  }, {
    "CompteNumber": "2193",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoIncorp",
    "RefCode": "AF"
  }, {
    "CompteNumber": "215",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoIncorp",
    "RefCode": "AG"
  }, {
    "CompteNumber": "216",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoIncorp",
    "RefCode": "AG"
  }, {
    "CompteNumber": "217",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoIncorp",
    "RefCode": "AH"
  }, {
    "CompteNumber": "218",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoIncorp",
    "RefCode": "AH"
  }, {
    "CompteNumber": "2198",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "ImmoIncorp",
    "RefCode": "AH"
  }, {
    "CompteNumber": "31",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BC"
  }, {
    "CompteNumber": "381",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BC"
  }, {
    "CompteNumber": "387",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BC"
  }, {
    "CompteNumber": "32",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BD"
  }, {
    "CompteNumber": "33",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BD"
  }, {
    "CompteNumber": "382",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BD"
  }, {
    "CompteNumber": "383",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BD"
  }, {
    "CompteNumber": "388",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BD"
  }, {
    "CompteNumber": "34",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BE"
  }, {
    "CompteNumber": "35",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BE"
  }, {
    "CompteNumber": "36",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BF"
  }, {
    "CompteNumber": "37",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BF"
  }, {
    "CompteNumber": "386",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BF"
  }, {
    "CompteNumber": "387",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "Stocks",
    "RefCode": "BF"
  }, {
    "CompteNumber": "50",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "TresorActif",
    "RefCode": "BQ"
  }, {
    "CompteNumber": "51",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "TresorActif",
    "RefCode": "BR"
  }, {
    "CompteNumber": "52",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "TresorActif",
    "RefCode": "BS"
  }, {
    "CompteNumber": "53",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "TresorActif",
    "RefCode": "BS"
  }, {
    "CompteNumber": "54",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "TresorActif",
    "RefCode": "BS"
  }, {
    "CompteNumber": "57",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "TresorActif",
    "RefCode": "BS"
  }, {
    "CompteNumber": "581",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "TresorActif",
    "RefCode": "BS"
  }, {
    "CompteNumber": "582",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblBilanActif",
    "AreaShortName": "TresorActif",
    "RefCode": "BS"
  }, {
    "CompteNumber": "2919",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AE"
  }, {
    "CompteNumber": "2912",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AF"
  }, {
    "CompteNumber": "2913",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AF"
  }, {
    "CompteNumber": "2914",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AF"
  }, {
    "CompteNumber": "2919",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AF"
  }, {
    "CompteNumber": "2915",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AG"
  }, {
    "CompteNumber": "2916",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AG"
  }, {
    "CompteNumber": "2917",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AH"
  }, {
    "CompteNumber": "2918",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AH"
  }, {
    "CompteNumber": "2919",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AH"
  }, {
    "CompteNumber": "292",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AJ"
  }, {
    "CompteNumber": "2931",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AK"
  }, {
    "CompteNumber": "2932",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AK"
  }, {
    "CompteNumber": "2933",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AK"
  }, {
    "CompteNumber": "2937",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AK"
  }, {
    "CompteNumber": "2939",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AK"
  }, {
    "CompteNumber": "2939",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AL"
  }, {
    "CompteNumber": "294",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AM"
  }, {
    "CompteNumber": "2949",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AM"
  }, {
    "CompteNumber": "2945",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AN"
  }, {
    "CompteNumber": "2949",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AN"
  }, {
    "CompteNumber": "295",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AP"
  }, {
    "CompteNumber": "296",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AR"
  }, {
    "CompteNumber": "297",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "AS"
  }, {
    "CompteNumber": "498",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BA"
  }, {
    "CompteNumber": "391",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BC"
  }, {
    "CompteNumber": "3981",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BC"
  }, {
    "CompteNumber": "392",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BD"
  }, {
    "CompteNumber": "393",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BD"
  }, {
    "CompteNumber": "398",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BD"
  }, {
    "CompteNumber": "394",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BE"
  }, {
    "CompteNumber": "395",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BE"
  }, {
    "CompteNumber": "396",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BF"
  }, {
    "CompteNumber": "397",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BF"
  }, {
    "CompteNumber": "398",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BF"
  }, {
    "CompteNumber": "490",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BH"
  }, {
    "CompteNumber": "491",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BI"
  }, {
    "CompteNumber": "492",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "493",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "495",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "496",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "497",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BJ"
  }, {
    "CompteNumber": "590",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BQ"
  }, {
    "CompteNumber": "591",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BR"
  }, {
    "CompteNumber": "592",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BS"
  }, {
    "CompteNumber": "593",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BS"
  }, {
    "CompteNumber": "594",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblActif",
    "StableauName": "tblProvision",
    "AreaShortName": "Provis",
    "RefCode": "BS"
  }, {
    "CompteNumber": "67",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgeFinanc",
    "RefCode": "SA"
  }, {
    "CompteNumber": "676",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgeFinanc",
    "RefCode": "SC"
  }, {
    "CompteNumber": "687",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgeFinanc",
    "RefCode": "SD"
  }, {
    "CompteNumber": "697",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgeFinanc",
    "RefCode": "SD"
  }, {
    "CompteNumber": "66",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgePerso",
    "RefCode": "RP"
  }, {
    "CompteNumber": "81",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesHAO",
    "RefCode": "SK"
  }, {
    "CompteNumber": "83",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesHAO",
    "RefCode": "SL"
  }, {
    "CompteNumber": "85",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesHAO",
    "RefCode": "SM"
  }, {
    "CompteNumber": "601",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesMBrutMarch",
    "RefCode": "RA"
  }, {
    "CompteNumber": "6031",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesMBrutMarch",
    "RefCode": "RB"
  }, {
    "CompteNumber": "602",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesMBrutMatier",
    "RefCode": "RC"
  }, {
    "CompteNumber": "6032",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesMBrutMatier",
    "RefCode": "RD"
  }, {
    "CompteNumber": "604",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesValAjout",
    "RefCode": "RE"
  }, {
    "CompteNumber": "605",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesValAjout",
    "RefCode": "RE"
  }, {
    "CompteNumber": "608",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesValAjout",
    "RefCode": "RE"
  }, {
    "CompteNumber": "6033",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesValAjout",
    "RefCode": "RH"
  }, {
    "CompteNumber": "61",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesValAjout",
    "RefCode": "RI"
  }, {
    "CompteNumber": "62",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesValAjout",
    "RefCode": "RJ"
  }, {
    "CompteNumber": "63",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesValAjout",
    "RefCode": "RJ"
  }, {
    "CompteNumber": "64",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesValAjout",
    "RefCode": "RK"
  }, {
    "CompteNumber": "65",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ChrgesValAjout",
    "RefCode": "RL"
  }, {
    "CompteNumber": "681",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "DotatAmortProv",
    "RefCode": "RS"
  }, {
    "CompteNumber": "691",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "DotatAmortProv",
    "RefCode": "RS"
  }, {
    "CompteNumber": "87",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ParticImpot",
    "RefCode": "SQ"
  }, {
    "CompteNumber": "89",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblCharges",
    "StableauName": "tblResultChrges",
    "AreaShortName": "ParticImpot",
    "RefCode": "SR"
  }, {
    "CompteNumber": "701",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblChifAffair",
    "StableauName": "tblChifAffair",
    "AreaShortName": "ProdMBrutMarch",
    "RefCode": "TA"
  }, {
    "CompteNumber": "702",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblChifAffair",
    "StableauName": "tblChifAffair",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TC"
  }, {
    "CompteNumber": "703",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblChifAffair",
    "StableauName": "tblChifAffair",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TC"
  }, {
    "CompteNumber": "704",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblChifAffair",
    "StableauName": "tblChifAffair",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TC"
  }, {
    "CompteNumber": "705",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblChifAffair",
    "StableauName": "tblChifAffair",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TD"
  }, {
    "CompteNumber": "706",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblChifAffair",
    "StableauName": "tblChifAffair",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TD"
  }, {
    "CompteNumber": "707",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblChifAffair",
    "StableauName": "tblChifAffair",
    "AreaShortName": "ProdValAjout",
    "RefCode": "TH"
  }, {
    "CompteNumber": "14",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "AutrCapiPro",
    "RefCode": "CL"
  }, {
    "CompteNumber": "15",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "AutrCapiPro",
    "RefCode": "CM"
  }, {
    "CompteNumber": "101",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "Capital",
    "RefCode": "CA"
  }, {
    "CompteNumber": "102",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "Capital",
    "RefCode": "CA"
  }, {
    "CompteNumber": "103",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "Capital",
    "RefCode": "CA"
  }, {
    "CompteNumber": "104",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "Capital",
    "RefCode": "CA"
  }, {
    "CompteNumber": "109",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "Capital",
    "RefCode": "CB"
  }, {
    "CompteNumber": "161",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DA"
  }, {
    "CompteNumber": "162",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DA"
  }, {
    "CompteNumber": "1661",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DA"
  }, {
    "CompteNumber": "1662",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DA"
  }, {
    "CompteNumber": "17",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DB"
  }, {
    "CompteNumber": "163",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DC"
  }, {
    "CompteNumber": "164",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DC"
  }, {
    "CompteNumber": "165",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DC"
  }, {
    "CompteNumber": "166",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DC"
  }, {
    "CompteNumber": "167",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DC"
  }, {
    "CompteNumber": "168",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DC"
  }, {
    "CompteNumber": "181",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DC"
  }, {
    "CompteNumber": "182",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DC"
  }, {
    "CompteNumber": "183",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DC"
  }, {
    "CompteNumber": "184",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "DetteFin",
    "RefCode": "DC"
  }, {
    "CompteNumber": "479",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "EcartConvPassif",
    "RefCode": "DV"
  }, {
    "CompteNumber": "481",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DH"
  }, {
    "CompteNumber": "482",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DH"
  }, {
    "CompteNumber": "483",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DH"
  }, {
    "CompteNumber": "484",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DH"
  }, {
    "CompteNumber": "4998",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DH"
  }, {
    "CompteNumber": "419",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DI"
  }, {
    "CompteNumber": "401",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DJ"
  }, {
    "CompteNumber": "402",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DJ"
  }, {
    "CompteNumber": "408",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DJ"
  }, {
    "CompteNumber": "441",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DK"
  }, {
    "CompteNumber": "442",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DK"
  }, {
    "CompteNumber": "443",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DK"
  }, {
    "CompteNumber": "4441",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DK"
  }, {
    "CompteNumber": "446",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DK"
  }, {
    "CompteNumber": "447",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DK"
  }, {
    "CompteNumber": "4486",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DK"
  }, {
    "CompteNumber": "4499",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DK"
  }, {
    "CompteNumber": "42",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DL"
  }, {
    "CompteNumber": "43",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DL"
  }, {
    "CompteNumber": "185",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DM"
  }, {
    "CompteNumber": "4712",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DM"
  }, {
    "CompteNumber": "472",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DM"
  }, {
    "CompteNumber": "477",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DM"
  }, {
    "CompteNumber": "499",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DN"
  }, {
    "CompteNumber": "599",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PassiCircul",
    "RefCode": "DN"
  }, {
    "CompteNumber": "105",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PrimeReserv",
    "RefCode": "CD"
  }, {
    "CompteNumber": "106",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PrimeReserv",
    "RefCode": "CE"
  }, {
    "CompteNumber": "111",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PrimeReserv",
    "RefCode": "CF"
  }, {
    "CompteNumber": "112",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PrimeReserv",
    "RefCode": "CF"
  }, {
    "CompteNumber": "113",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PrimeReserv",
    "RefCode": "CF"
  }, {
    "CompteNumber": "118",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PrimeReserv",
    "RefCode": "CG"
  }, {
    "CompteNumber": "12",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "PrimeReserv",
    "RefCode": "CH"
  }, {
    "CompteNumber": "19",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "ProviFin_Prov",
    "RefCode": "DD"
  }, {
    "CompteNumber": "131",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "ResultExerc",
    "RefCode": "CI"
  }, {
    "CompteNumber": "139",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "ResultExerc",
    "RefCode": "CI"
  }, {
    "CompteNumber": "564",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "TresorPassi",
    "RefCode": "DQ"
  }, {
    "CompteNumber": "565",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "TresorPassi",
    "RefCode": "DQ"
  }, {
    "CompteNumber": "561",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "TresorPassi",
    "RefCode": "DR"
  }, {
    "CompteNumber": "566",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "TresorPassi",
    "RefCode": "DR"
  }, {
    "CompteNumber": "52",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblPassif",
    "StableauName": "tblBilanPassif",
    "AreaShortName": "TresorPassi",
    "RefCode": "DS"
  }, {
    "CompteNumber": "701",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdMBrutMarch",
    "RefCode": "TA"
  }, {
    "CompteNumber": "702",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TC"
  }, {
    "CompteNumber": "703",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TC"
  }, {
    "CompteNumber": "704",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TC"
  }, {
    "CompteNumber": "705",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TD"
  }, {
    "CompteNumber": "706",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TD"
  }, {
    "CompteNumber": "73",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TE"
  }, {
    "CompteNumber": "72",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdMBrutMatier",
    "RefCode": "TF"
  }, {
    "CompteNumber": "77",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdtFinanc",
    "RefCode": "UA"
  }, {
    "CompteNumber": "776",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdtFinanc",
    "RefCode": "UC"
  }, {
    "CompteNumber": "797",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdtFinanc",
    "RefCode": "UD"
  }, {
    "CompteNumber": "787",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdtFinanc",
    "RefCode": "UE"
  }, {
    "CompteNumber": "82",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdtHAO",
    "RefCode": "UK"
  }, {
    "CompteNumber": "84",
    "Exception": 1,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdtHAO",
    "RefCode": "UL"
  }, {
    "CompteNumber": "88",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdtHAO",
    "RefCode": "UL"
  }, {
    "CompteNumber": "86",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdtHAO",
    "RefCode": "UM"
  }, {
    "CompteNumber": "848",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdtHAO",
    "RefCode": "UN"
  }, {
    "CompteNumber": "707",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdValAjout",
    "RefCode": "TH"
  }, {
    "CompteNumber": "71",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdValAjout",
    "RefCode": "TK"
  }, {
    "CompteNumber": "75",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "ProdValAjout",
    "RefCode": "TL"
  }, {
    "CompteNumber": "791",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "RepriProv",
    "RefCode": "TS"
  }, {
    "CompteNumber": "798",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "RepriProv",
    "RefCode": "TS"
  }, {
    "CompteNumber": "781",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblProduidts",
    "StableauName": "tblResultPrdts",
    "AreaShortName": "TransfChrge",
    "RefCode": "TT"
  }, {
    "CompteNumber": "137",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblResultat",
    "StableauName": "tblResultat",
    "AreaShortName": "tblResultActOrd",
    "RefCode": "UI"
  }, {
    "CompteNumber": "134",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblResultat",
    "StableauName": "tblResultat",
    "AreaShortName": "tblResultExBruExpl",
    "RefCode": "TQ"
  }, {
    "CompteNumber": "135",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblResultat",
    "StableauName": "tblResultat",
    "AreaShortName": "tblResultExpl",
    "RefCode": "TX"
  }, {
    "CompteNumber": "136",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblResultat",
    "StableauName": "tblResultat",
    "AreaShortName": "tblResultFinanc ",
    "RefCode": "UG"
  }, {
    "CompteNumber": "138",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblResultat",
    "StableauName": "tblResultat",
    "AreaShortName": "tblResultHOA",
    "RefCode": "UP"
  }, {
    "CompteNumber": "1321",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblResultat",
    "StableauName": "tblResultat",
    "AreaShortName": "tblResultMBrutMarch",
    "RefCode": "TB"
  }, {
    "CompteNumber": "1322",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblResultat",
    "StableauName": "tblResultat",
    "AreaShortName": "tblResultMBrutMatier",
    "RefCode": "TG"
  }, {
    "CompteNumber": "131",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblResultat",
    "StableauName": "tblResultat",
    "AreaShortName": "tblResultNet",
    "RefCode": "UZ"
  }, {
    "CompteNumber": "133",
    "Exception": 0,
    "Taux": 1,
    "TableauName": "tblResultat",
    "StableauName": "tblResultat",
    "AreaShortName": "tblResultValAjout",
    "RefCode": "TN"
  },

];
module.exports = ocompterefencedata;
