var oreportdetaildata = [
  {
    "ReportName": "tblActif",
    "RefCode": "AA",
    "olevelNum": "3",
    "SortOrder": "1000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CA",
    "olevelNum": "3",
    "SortOrder": "1000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TA",
    "olevelNum": "4",
    "SortOrder": "1000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RA",
    "olevelNum": "4",
    "SortOrder": "1000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CB",
    "olevelNum": "3",
    "SortOrder": "2000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AX",
    "olevelNum": "4",
    "SortOrder": "2000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RB",
    "olevelNum": "4",
    "SortOrder": "2000"
  }, {
    "ReportName": "tblResultat",
    "RefCode": "TB",
    "olevelNum": "5",
    "SortOrder": "2000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CC",
    "olevelNum": "4",
    "SortOrder": "3000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AY",
    "olevelNum": "4",
    "SortOrder": "3000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RC",
    "olevelNum": "4",
    "SortOrder": "3000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TC",
    "olevelNum": "4",
    "SortOrder": "3000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AC",
    "olevelNum": "4",
    "SortOrder": "4000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RD",
    "olevelNum": "4",
    "SortOrder": "4000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CD",
    "olevelNum": "4",
    "SortOrder": "4000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TD",
    "olevelNum": "4",
    "SortOrder": "4000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AD",
    "olevelNum": "3",
    "SortOrder": "5000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CE",
    "olevelNum": "4",
    "SortOrder": "5000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TE",
    "olevelNum": "4",
    "SortOrder": "5000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RE",
    "olevelNum": "4",
    "SortOrder": "5000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AE",
    "olevelNum": "4",
    "SortOrder": "6000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CF",
    "olevelNum": "4",
    "SortOrder": "6000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TF",
    "olevelNum": "4",
    "SortOrder": "6000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RH",
    "olevelNum": "4",
    "SortOrder": "6000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AF",
    "olevelNum": "4",
    "SortOrder": "7000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CG",
    "olevelNum": "4",
    "SortOrder": "7000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RI",
    "olevelNum": "4",
    "SortOrder": "7000"
  }, {
    "ReportName": "tblResultat",
    "RefCode": "TG",
    "olevelNum": "5",
    "SortOrder": "7000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AG",
    "olevelNum": "4",
    "SortOrder": "8000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TH",
    "olevelNum": "4",
    "SortOrder": "8000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RJ",
    "olevelNum": "4",
    "SortOrder": "8000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CH",
    "olevelNum": "4",
    "SortOrder": "8000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CI",
    "olevelNum": "3",
    "SortOrder": "9000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AH",
    "olevelNum": "4",
    "SortOrder": "9000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RK",
    "olevelNum": "4",
    "SortOrder": "9000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AI",
    "olevelNum": "3",
    "SortOrder": "10000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CK",
    "olevelNum": "4",
    "SortOrder": "10000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RL",
    "olevelNum": "4",
    "SortOrder": "10000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AJ",
    "olevelNum": "4",
    "SortOrder": "11000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CL",
    "olevelNum": "4",
    "SortOrder": "11000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TK",
    "olevelNum": "4",
    "SortOrder": "11000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RP",
    "olevelNum": "4",
    "SortOrder": "11000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AK",
    "olevelNum": "4",
    "SortOrder": "12000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TL",
    "olevelNum": "4",
    "SortOrder": "12000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CM",
    "olevelNum": "4",
    "SortOrder": "12000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CP",
    "olevelNum": "2",
    "SortOrder": "13000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AL",
    "olevelNum": "4",
    "SortOrder": "13000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RS",
    "olevelNum": "4",
    "SortOrder": "13000"
  }, {
    "ReportName": "tblResultat",
    "RefCode": "TN",
    "olevelNum": "5",
    "SortOrder": "13000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AM",
    "olevelNum": "4",
    "SortOrder": "14000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RW",
    "olevelNum": "3",
    "SortOrder": "14000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DA",
    "olevelNum": "4",
    "SortOrder": "14000"
  }, {
    "ReportName": "tblResultat",
    "RefCode": "TQ",
    "olevelNum": "5",
    "SortOrder": "14000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AN",
    "olevelNum": "4",
    "SortOrder": "15000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DB",
    "olevelNum": "4",
    "SortOrder": "15000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SA",
    "olevelNum": "4",
    "SortOrder": "15000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TS",
    "olevelNum": "4",
    "SortOrder": "15000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AP",
    "olevelNum": "3",
    "SortOrder": "16000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AP",
    "olevelNum": "4",
    "SortOrder": "16000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TT",
    "olevelNum": "4",
    "SortOrder": "16000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DC",
    "olevelNum": "4",
    "SortOrder": "16000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SC",
    "olevelNum": "4",
    "SortOrder": "16000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TW",
    "olevelNum": "3",
    "SortOrder": "17000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AQ",
    "olevelNum": "3",
    "SortOrder": "17000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DD",
    "olevelNum": "4",
    "SortOrder": "17000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SD",
    "olevelNum": "4",
    "SortOrder": "17000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SF",
    "olevelNum": "3",
    "SortOrder": "18000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AR",
    "olevelNum": "4",
    "SortOrder": "18000"
  }, {
    "ReportName": "tblResultat",
    "RefCode": "TX",
    "olevelNum": "5",
    "SortOrder": "18000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SH",
    "olevelNum": "2",
    "SortOrder": "19000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DF",
    "olevelNum": "2",
    "SortOrder": "19000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AS",
    "olevelNum": "4",
    "SortOrder": "19000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SK",
    "olevelNum": "4",
    "SortOrder": "20000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UA",
    "olevelNum": "4",
    "SortOrder": "20000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UC",
    "olevelNum": "4",
    "SortOrder": "21000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SL",
    "olevelNum": "4",
    "SortOrder": "21000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AZ",
    "olevelNum": "2",
    "SortOrder": "22000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DH",
    "olevelNum": "4",
    "SortOrder": "22000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SM",
    "olevelNum": "4",
    "SortOrder": "22000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UD",
    "olevelNum": "4",
    "SortOrder": "22000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SO",
    "olevelNum": "2",
    "SortOrder": "23000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DI",
    "olevelNum": "4",
    "SortOrder": "23000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UE",
    "olevelNum": "4",
    "SortOrder": "23000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UF",
    "olevelNum": "3",
    "SortOrder": "24000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BA",
    "olevelNum": "3",
    "SortOrder": "24000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BA",
    "olevelNum": "4",
    "SortOrder": "24000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SQ",
    "olevelNum": "4",
    "SortOrder": "24000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DJ",
    "olevelNum": "4",
    "SortOrder": "24000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BB",
    "olevelNum": "3",
    "SortOrder": "25000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DK",
    "olevelNum": "4",
    "SortOrder": "25000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SR",
    "olevelNum": "4",
    "SortOrder": "25000"
  }, {
    "ReportName": "tblResultat",
    "RefCode": "UG",
    "olevelNum": "5",
    "SortOrder": "25000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UH",
    "olevelNum": "2",
    "SortOrder": "26000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "SS",
    "olevelNum": "2",
    "SortOrder": "26000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BC",
    "olevelNum": "4",
    "SortOrder": "26000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DL",
    "olevelNum": "4",
    "SortOrder": "26000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "ST",
    "olevelNum": "1",
    "SortOrder": "27000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BD",
    "olevelNum": "4",
    "SortOrder": "27000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DM",
    "olevelNum": "4",
    "SortOrder": "27000"
  }, {
    "ReportName": "tblResultat",
    "RefCode": "UI",
    "olevelNum": "5",
    "SortOrder": "27000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BE",
    "olevelNum": "4",
    "SortOrder": "28000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DN",
    "olevelNum": "4",
    "SortOrder": "28000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DP",
    "olevelNum": "2",
    "SortOrder": "29000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BF",
    "olevelNum": "4",
    "SortOrder": "29000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UK",
    "olevelNum": "4",
    "SortOrder": "29000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BG",
    "olevelNum": "3",
    "SortOrder": "30000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DQ",
    "olevelNum": "4",
    "SortOrder": "30000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UL",
    "olevelNum": "4",
    "SortOrder": "30000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BH",
    "olevelNum": "4",
    "SortOrder": "31000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UM",
    "olevelNum": "4",
    "SortOrder": "31000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DR",
    "olevelNum": "4",
    "SortOrder": "31000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BI",
    "olevelNum": "4",
    "SortOrder": "32000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DS",
    "olevelNum": "4",
    "SortOrder": "32000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UN",
    "olevelNum": "4",
    "SortOrder": "32000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DT",
    "olevelNum": "2",
    "SortOrder": "33000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UO",
    "olevelNum": "2",
    "SortOrder": "33000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BJ",
    "olevelNum": "4",
    "SortOrder": "33000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DV",
    "olevelNum": "2",
    "SortOrder": "34000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BK",
    "olevelNum": "2",
    "SortOrder": "34000"
  }, {
    "ReportName": "tblResultat",
    "RefCode": "UP",
    "olevelNum": "5",
    "SortOrder": "34000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DZ",
    "olevelNum": "1",
    "SortOrder": "35000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UT",
    "olevelNum": "1",
    "SortOrder": "35000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BQ",
    "olevelNum": "4",
    "SortOrder": "35000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BR",
    "olevelNum": "4",
    "SortOrder": "36000"
  }, {
    "ReportName": "tblResultat",
    "RefCode": "UZ",
    "olevelNum": "5",
    "SortOrder": "36000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BS",
    "olevelNum": "4",
    "SortOrder": "37000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BT",
    "olevelNum": "2",
    "SortOrder": "38000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BT",
    "olevelNum": "3",
    "SortOrder": "38000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BU",
    "olevelNum": "2",
    "SortOrder": "39000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BU",
    "olevelNum": "3",
    "SortOrder": "39000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BU",
    "olevelNum": "4",
    "SortOrder": "39000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "BZ",
    "olevelNum": "1",
    "SortOrder": "40000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CA",
    "olevelNum": "4",
    "SortOrder": "1500"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CB",
    "olevelNum": "4",
    "SortOrder": "2500"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DV",
    "olevelNum": "4",
    "SortOrder": "34500"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "CI",
    "olevelNum": "4",
    "SortOrder": "9500"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DG",
    "olevelNum": "2",
    "SortOrder": "20000"
  }, {
    "ReportName": "tblActif",
    "RefCode": "AW",
    "olevelNum": "4",
    "SortOrder": "20000"
  }, {
    "ReportName": "tblPassif",
    "RefCode": "DE",
    "olevelNum": "4",
    "SortOrder": "18000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "TJ",
    "olevelNum": "4",
    "SortOrder": "10000"
  }, {
    "ReportName": "tblResultat",
    "RefCode": "TI",
    "olevelNum": "5",
    "SortOrder": "9000"
  }, {
    "ReportName": "tblProduidts",
    "RefCode": "UJ",
    "olevelNum": "4",
    "SortOrder": "25000"
  }, {
    "ReportName": "tblCharges",
    "RefCode": "RQ",
    "olevelNum": "4",
    "SortOrder": "12000"
  }/*, {
    "ReportName": "tblTAFIRE",
    "RefCode": "FA",
    "olevelNum": "6",
    "SortOrder": "80500"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FB",
    "olevelNum": "6",
    "SortOrder": "81000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FC",
    "olevelNum": "6",
    "SortOrder": "82000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FD",
    "olevelNum": "6",
    "SortOrder": "83000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FF",
    "olevelNum": "6",
    "SortOrder": "84000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FG",
    "olevelNum": "6",
    "SortOrder": "85000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FH",
    "olevelNum": "6",
    "SortOrder": "86000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FI",
    "olevelNum": "6",
    "SortOrder": "87000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FJ",
    "olevelNum": "6",
    "SortOrder": "88000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FK",
    "olevelNum": "6",
    "SortOrder": "89000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FL",
    "olevelNum": "6",
    "SortOrder": "90000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FM",
    "olevelNum": "6",
    "SortOrder": "91000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FN",
    "olevelNum": "6",
    "SortOrder": "92000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FP",
    "olevelNum": "6",
    "SortOrder": "93000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FQ",
    "olevelNum": "6",
    "SortOrder": "94000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FR",
    "olevelNum": "6",
    "SortOrder": "95000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FS",
    "olevelNum": "6",
    "SortOrder": "96000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FT",
    "olevelNum": "6",
    "SortOrder": "97000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FU",
    "olevelNum": "6",
    "SortOrder": "98000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FV",
    "olevelNum": "6",
    "SortOrder": "99000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "FW",
    "olevelNum": "6",
    "SortOrder": "100000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZA",
    "olevelNum": "6",
    "SortOrder": "80000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZB",
    "olevelNum": "6",
    "SortOrder": "80900"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZD",
    "olevelNum": "6",
    "SortOrder": "82500"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZL",
    "olevelNum": "6",
    "SortOrder": "89500"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZM",
    "olevelNum": "6",
    "SortOrder": "90500"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZQ",
    "olevelNum": "6",
    "SortOrder": "93500"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZU",
    "olevelNum": "6",
    "SortOrder": "97500"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZA",
    "olevelNum": "6",
    "SortOrder": "80000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZB",
    "olevelNum": "6",
    "SortOrder": "80900"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZC",
    "olevelNum": "6",
    "SortOrder": "105000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZD",
    "olevelNum": "6",
    "SortOrder": "82500"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZE",
    "olevelNum": "6",
    "SortOrder": "107000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZF",
    "olevelNum": "6",
    "SortOrder": "108000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZG",
    "olevelNum": "6",
    "SortOrder": "109000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZH",
    "olevelNum": "6",
    "SortOrder": "103000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZI",
    "olevelNum": "6",
    "SortOrder": "110000"
  }, {
    "ReportName": "tblTafire",
    "RefCode": "ZJ",
    "olevelNum": "6",
    "SortOrder": "111000"
  }, {
    "ReportName": "tblTAFIRE",
    "RefCode": "FZ",
    "olevelNum": "6",
    "SortOrder": "200000"
  }*/
];
module.exports = oreportdetaildata;
